# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                    Animations Configuration                 ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# https://wiki.hyprland.org/Configuring/Animations/



animations {
    enabled = yes
    bezier = overshot, 0.13, 0.99, 0.29, 1.0
    #animation = NAME,          ONOFF,  SPEED,  CURVE,       [STYLE]
    #                                   in ds
    animation = windowsIn,      1,      1,      overshot,   slide
    animation = windowsOut,     1,      1,      default,    popin 80%
    animation = border,         1,      1,      default,
    animation = workspacesIn,   1,      1,      overshot,   slide
    animation = workspacesOut,  1,      1,      overshot,   slidefade 80%
    animation = monitorAdded,   1,      30,      overshot,   
}
