# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                     Defaults Configuration                  ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛


# General
$applauncher = wofi
$terminal2 = alacritty
$terminal = kitty
$browser = brave
$filemanager = kitty yazi
#$browser = zen-browser
$lockscreen = hyprlock
$mailclient = betterbird

# Screenshots
$shot-region = grimblast copy area
$shot-window = grimblast copy active
$shot-screen = grimblast copy output

# Wallpaper
$wallpaper-dir = ~/wallpapers
$wallpaper-set-selector = ~/.config/wallpaper/wallpaper-set-selector.sh $wallpaper-dir

#Power Menu
$power-menu = ~/.config/powermenu/launch.sh