# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                      Input Configuration                    ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# Input wiki https://wiki.hyprland.org/Configuring/Variables/#input

input {
    #0 - Cursor movement will not change focus.
    #1 - Cursor movement will always change focus to the window under the cursor.
    #2 - Cursor focus will be detached from keyboard focus. Clicking on a window will move keyboard focus to that window.
    #3 - Cursor focus will be completely separate from keyboard focus. Clicking on a window will not change keyboard focus.
    follow_mouse = 2 # 0|1|2|3
    float_switch_override_focus = 2
    kb_layout = de,us-german-umlaut
    kb_variant = nodeadkeys,
    kb_options = caps:escape_shifted_capslock,grp:rctrl_rshift_toggle
    repeat_rate = 60
    repeat_delay = 300
}

# Wacom - Tablet and Stylus configuration
device {
    name = wcom016a:00-2d1f:0185-stylus
    transform = 0
    output = eDP-1
}

# Touchscreen configuration
device {
    name = gxtp7936:00-27c6:0123
    transform = 0
    output = eDP-1
    enabled = true
}
