# preload = ~/.config/wallpaper/.current_wallpaper
# wallpaper = , ~/.config/wallpaper/.current_wallpaper
# wallpaper {
#     monitor = 
#     path = ~/.config/wallpaper/.current_wallpaper
# }

ipc = on
splash = false
