source = ~/.config/hypr/hyprlock_colors.conf

# BACKGROUND
background {
    monitor =
    #path = screenshot
    path = ~/.config/wallpaper/.current_wallpaper
    #color = $background
    blur_passes = 2
    # blur_size = 1
    contrast = 1
    brightness = 0.5
    vibrancy = 0.2
    vibrancy_darkness = 0.2
    crossfade_time = 3
    # reload with SIGUSR2
    reload_time = 0
}

# GENERAL
general {
    # no_fade_in = true
    # no_fade_out = true
    hide_cursor = true
    # grace = 0
    # disable_loading_bar = true
    ignore_empty_input = true
}

# $outer_color = rgba(0, 0, 0, 0)
# $inner_color = rgba(0, 0, 0, 0.2)
# $input_font_color = rgba(205, 214, 244, 1.0)
$check_color = rgb(204, 136, 34)
$numlock_color = rgb(120, 19, 227)
$capslock_color = rgba(204, 34, 34, 1)
# $bothlock_color = rgba(204, 34, 34, 1)

# INPUT FIELD
input-field {
    monitor =
    size = 250, 60
    outline_thickness = 2
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.35 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    outer_color = $input_outer_color
    inner_color = $input_inner_color
    font_color = $input_font_color
    fade_on_empty = true
    rounding = -1
    check_color = $check_color
    capslock_color = $capslock_color
    # numlock_color = $numlock_color
    invert_numlock = true
    # bothlock_color = $bothlock_color
    # placeholder_text = <i><span foreground="$input_font_color">Input Password...</span></i>
    placeholder_text = input password...
    hide_input = false
    position = 0, -200
    halign = center
    valign = center
}

# $clock_color = rgba(242, 243, 244, 0.75)
# $clock_color = rgba(198, 11, 11, 0.75)

# DATE
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%A, %B %d")"
    color = $clock_color
    font_size = 22
    font_family = JetBrains Mono
    position = 0, 300
    halign = center
    valign = center
}

# TIME
label {
    monitor = 
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = $clock_color
    font_size = 95
    font_family = JetBrains Mono Extrabold
    position = 0, 200
    halign = center
    valign = center
}

# FINGERPRINT AUTH
auth {
    fingerprint:enabled = true
    fingerprint:ready_message = scan finger
    fingerprint:present_message = scanning...
}