#!/usr/bin/zsh
# Thin orchestrator. The real config lives in modular files under
# $ZDOTDIR/rc.d (logical sections) and $ZDOTDIR/lib + $ZDOTDIR/modules
# (helpers and per-package modules). See each file's header for details.

# zmodload zsh/zprof  # uncomment (with `zprof` at EOF) to profile startup

# Powerlevel10k instant prompt — MUST stay near the top, before anything that
# prints output or reads input. Sources the cached prompt so the shell paints
# immediately; the rest of startup then runs "behind" the visible prompt.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
    source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# When unset, point at the modular config dir. VSCode's shell integration
# re-exports ZDOTDIR=$HOME when it was originally empty, so treat that as unset
# too — otherwise we'd look for rc.d under $HOME instead of ~/.config/zsh.
if [[ -z "$ZDOTDIR" || "$ZDOTDIR" == "$HOME" ]]; then
    ZDOTDIR="$HOME/.config/zsh"
fi

# Explicit, ordered source list (not a glob) so load order stays obvious:
# plugins/prompt/completion → interactive options → per-package modules.
for rc in plugins interactive modules; do
    source "$ZDOTDIR/rc.d/${rc}.zsh"
done
unset rc

# p10k user customization (generated by `p10k configure`).
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# zprof  # uncomment (with `zmodload zsh/zprof` at top) to profile startup
