# Font settings
font_family      JetBrainsMono Nerd Font
bold_font        JetBrainsMono Nerd Font Bold
italic_font      JetBrainsMono Nerd Font Italic
bold_italic_font JetBrainsMono Nerd Font Bold Italic
font_size 11.0

# Cursor settings
cursor_shape beam
cursor_blink_interval 0
cursor_trail 1
cursor_trail_decay 0.05 0.15
cursor_trail_start_threshold 2

#Display server
linux_display_server wayland

# Window settings
window_padding_width 3
scrollbar_width 0.5
background_opacity 0.85
dynamic_background_opacity yes
background_blur 10
hide_window_decorations no
wayland_titlebar_color background

# Scrolling
scrollback_lines 20000
scrollbar scrolled-and-hovered
scrollbar_gap 0.7
scrollbar_radius 0.5

# Mouse settings
mouse_hide_wait -1

# Copy and paste settings
copy_on_select no
paste_actions quote-urls-at-prompt,confirm

# Selection
select_by_word_characters @-./_~?&=%+#

# Colors - Nord theme
foreground #E5E9F0
# background #2E3440
background #1a1a1a
background #181818

# Normal colors
color0  #3B4252
color1  #BF616A
color2  #A3BE8C
color3  #EBCB8B
color4  #81A1C1
color5  #B48EAD
color6  #88C0D0
color7  #E5E9F0

# Bright colors
color8  #4C566A
color9  #BF616A
color10 #A3BE8C
color11 #EBCB8B
color12 #81A1C1
color13 #B48EAD
color14 #8FBCBB
color15 #ECEFF4

# Keyboard bindings
map ctrl+shift+enter new_os_window

#hyprlinks
show_hyperlink_targets yes
underline_hyperlinks hover
detect_urls yes

confirm_os_window_close 0